/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/PageLayout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/PageLayout/AppHeader.vue')['default']
    AppSideMenu: typeof import('./components/PageLayout/AppSideMenu.vue')['default']
    AppSidePanel: typeof import('./components/PageLayout/AppSidePanel.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
