/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOwner: typeof import('./components/templates/ManageAppsComponents/_Contact/AddOwner.vue')['default']
    AppFooter: typeof import('./components/PageLayout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/PageLayout/AppHeader.vue')['default']
    AppSideMenu: typeof import('./components/PageLayout/AppSideMenu.vue')['default']
    AppSidePanel: typeof import('./components/PageLayout/AppSidePanel.vue')['default']
    Contact: typeof import('./components/templates/ManageAppsComponents/Contact.vue')['default']
    ContactAddUserDialog: typeof import('./components/templates/ManageAppsComponents/_Contact/ContactAddUserDialog.vue')['default']
    ContactRemoveUserDialog: typeof import('./components/templates/ManageAppsComponents/_Contact/ContactRemoveUserDialog.vue')['default']
    CreateApp: typeof import('./components/templates/ManageAppsComponents/CreateApp.vue')['default']
    DataTable: typeof import('./components/templates/ManageUserComponents/DataTable.vue')['default']
    DataTableMP: typeof import('./components/templates/ManagePermissionsComponents/DataTableMP.vue')['default']
    DataTables: typeof import('./components/templates/ManageGroupsComponents/DataTables.vue')['default']
    Details: typeof import('./components/templates/ManagePermissionsComponents/DataTableMPActions/Details.vue')['default']
    EditApp: typeof import('./components/templates/ManageAppsComponents/EditApp.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ManageGroupsAddGroup: typeof import('./components/templates/ManageGroupsComponents/ManageGroupsAddGroup.vue')['default']
    ManageGroupsAddMember: typeof import('./components/templates/ManageGroupsComponents/ManageGroupsAddMember.vue')['default']
    ManageGroupsChangeGroupStatus: typeof import('./components/templates/ManageGroupsComponents/ManageGroupsChangeGroupStatus.vue')['default']
    ManageGroupsChangeMemberStatus: typeof import('./components/templates/ManageGroupsComponents/ManageGroupsChangeMemberStatus.vue')['default']
    ManageGroupsDeleteGroup: typeof import('./components/templates/ManageGroupsComponents/ManageGroupsDeleteGroup.vue')['default']
    ManageGroupsEditGroup: typeof import('./components/templates/ManageGroupsComponents/ManageGroupsEditGroup.vue')['default']
    ManageGroupsGroupMenu: typeof import('./components/templates/ManageGroupsComponents/ManageGroupsGroupMenu.vue')['default']
    ManageGroupsRemoveMember: typeof import('./components/templates/ManageGroupsComponents/ManageGroupsRemoveMember.vue')['default']
    ManageGroupsUpdateGroup: typeof import('./components/templates/ManageGroupsComponents/ManageGroupsUpdateGroup.vue')['default']
    ManageUserActivityChangeDialog: typeof import('./components/templates/ManageUserComponents/ManageUserActivityChangeDialog.vue')['default']
    ManageUserChangePasswordDialog: typeof import('./components/templates/ManageUserComponents/ManageUserChangePasswordDialog.vue')['default']
    ManageUserCreateDialog: typeof import('./components/templates/ManageUserComponents/ManageUserCreateDialog.vue')['default']
    ManageUserEditDialog: typeof import('./components/templates/ManageUserComponents/ManageUserEditDialog.vue')['default']
    ManageUserRemoveDialog: typeof import('./components/templates/ManageUserComponents/ManageUserRemoveDialog.vue')['default']
    Menus: typeof import('./components/templates/ManageAppsComponents/Menus.vue')['default']
    Panels: typeof import('./components/templates/ManageAppsComponents/Panels.vue')['default']
    PermDetails: typeof import('./components/templates/ManagePermissionsComponents/DataTableMPActions/PermDetails.vue')['default']
    Permissions: typeof import('./components/templates/ManagePermissionsComponents/Permissions.vue')['default']
    PermissionsUser: typeof import('./components/templates/ManagePermissionsComponents/PermissionsUser.vue')['default']
    RemoveApp: typeof import('./components/templates/ManageAppsComponents/RemoveApp.vue')['default']
    RemoveOwner: typeof import('./components/templates/ManageAppsComponents/_Contact/RemoveOwner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/multiuse/Snackbar.vue')['default']
  }
}
