// <auto-generated />
using System;
using GlobalManagement.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlobalManagement.Migrations
{
    [DbContext(typeof(GlobalDatabase))]
    [Migration("20241218074110_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalManagement.Logging._Log_Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("GlobalManagement.Models.AppModel.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Application Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Application Name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("Application");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "10.35.92.163:3001",
                            CreatedAt = new DateTime(2024, 12, 18, 8, 41, 10, 206, DateTimeKind.Local).AddTicks(8820),
                            Description = "Application used to manage other applications and permission",
                            IsActive = true,
                            Name = "GlobalApp",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Uuid = new Guid("899960d1-f610-4c7d-878e-b505b5fe7209")
                        },
                        new
                        {
                            Id = 2,
                            Address = "10.35.92.163:2999",
                            CreatedAt = new DateTime(2024, 12, 18, 8, 41, 10, 206, DateTimeKind.Local).AddTicks(8883),
                            Description = "Application used to manage reference, ecr, deviation",
                            IsActive = true,
                            Name = "ControlReport",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Uuid = new Guid("37f9aec4-3090-473d-a771-159a4bee8c47")
                        });
                });

            modelBuilder.Entity("GlobalManagement.Models.AppModel._App.AppOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AppUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("ApplicationOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUuid = new Guid("899960d1-f610-4c7d-878e-b505b5fe7209"),
                            Uuid = new Guid("77847e48-76c5-498f-8b96-615323e5b66b")
                        },
                        new
                        {
                            Id = 2,
                            AppUuid = new Guid("37f9aec4-3090-473d-a771-159a4bee8c47"),
                            Uuid = new Guid("b43613ac-688a-4daf-b00a-b7a832a24d85")
                        });
                });

            modelBuilder.Entity("GlobalManagement.Models.AppModel._App.AppOwners", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AppUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("ApplicationOwner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUuid = new Guid("899960d1-f610-4c7d-878e-b505b5fe7209"),
                            UserUuid = new Guid("231811de-77b8-4637-9118-c6544126b68b"),
                            Uuid = new Guid("9daa8368-c34d-491f-bca9-9e8171013f74")
                        },
                        new
                        {
                            Id = 2,
                            AppUuid = new Guid("37f9aec4-3090-473d-a771-159a4bee8c47"),
                            UserUuid = new Guid("37f9aec4-3090-473d-a771-159a4bee8c47"),
                            Uuid = new Guid("3be46db9-8644-4007-addb-b92f66743b98")
                        });
                });

            modelBuilder.Entity("GlobalManagement.Models.Groups.GroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GlobalManagement.Models.Groups.Members.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupUUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("GlobalManagement.Models.Groups.Permissions.GroupPermissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("UsersCanAccessGlobalApp")
                        .HasColumnType("bit");

                    b.Property<bool>("UsersCanAccessReferenceHub")
                        .HasColumnType("bit");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("GroupPermissions");
                });

            modelBuilder.Entity("GlobalManagement.Models.Groups._Default.GroupRoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAddRoles")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddUser")
                        .HasColumnType("bit");

                    b.Property<bool>("CanModifyGroup")
                        .HasColumnType("bit");

                    b.Property<bool>("CanModifyRoles")
                        .HasColumnType("bit");

                    b.Property<bool>("CanModifyUser")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRemoveGroup")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRemoveRoles")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRemoveUser")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRoleRemovable")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("GroupRole");
                });

            modelBuilder.Entity("GlobalManagement.Models.Permissions.PermissionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AppUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("UUID");

                    b.ToTable("ApplicationPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppName = "GlobalApp",
                            AppUuid = new Guid("899960d1-f610-4c7d-878e-b505b5fe7209"),
                            CreatedAt = new DateTime(2024, 12, 18, 8, 41, 10, 379, DateTimeKind.Local).AddTicks(2704),
                            Role = "Administrator",
                            RoleUuid = new Guid("02cc50eb-c871-41e0-87b0-b44c8d4a00d5"),
                            UUID = new Guid("f0d6b5ef-b86a-4ddf-ae05-fe20fbf23577"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserUuid = new Guid("231811de-77b8-4637-9118-c6544126b68b")
                        },
                        new
                        {
                            Id = 2,
                            AppName = "ControlReport",
                            AppUuid = new Guid("37f9aec4-3090-473d-a771-159a4bee8c47"),
                            CreatedAt = new DateTime(2024, 12, 18, 8, 41, 10, 379, DateTimeKind.Local).AddTicks(2784),
                            Role = "Administrator",
                            RoleUuid = new Guid("e12d1ec2-9904-40aa-be78-748198ba8a79"),
                            UUID = new Guid("91e1a274-4c7c-4cb8-b0f3-7eb3e7cb8035"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserUuid = new Guid("231811de-77b8-4637-9118-c6544126b68b")
                        });
                });

            modelBuilder.Entity("GlobalManagement.Models._DefaultModels._Roles._ControlReportRoles.DefaultControlReportRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AppUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanBeEdited")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateDeviation")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateEcr")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateIntervention")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateReference")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateTask")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteDeviation")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteEcr")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteIntervention")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteReference")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteTask")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReadDeviation")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReadEcr")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReadIntervention")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReadReference")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReadTask")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdateDeviation")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdateEcr")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdateIntervention")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdateReference")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdateTask")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUseApp")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAllPrivelage")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("UUID");

                    b.ToTable("ControlReportPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppName = "ControlReport",
                            AppUuid = new Guid("37f9aec4-3090-473d-a771-159a4bee8c47"),
                            CanBeEdited = false,
                            CanCreateDeviation = true,
                            CanCreateEcr = true,
                            CanCreateIntervention = true,
                            CanCreateReference = true,
                            CanCreateTask = true,
                            CanDeleteDeviation = false,
                            CanDeleteEcr = true,
                            CanDeleteIntervention = true,
                            CanDeleteReference = true,
                            CanDeleteTask = true,
                            CanReadDeviation = true,
                            CanReadEcr = true,
                            CanReadIntervention = true,
                            CanReadReference = true,
                            CanReadTask = true,
                            CanUpdateDeviation = true,
                            CanUpdateEcr = true,
                            CanUpdateIntervention = true,
                            CanUpdateReference = true,
                            CanUpdateTask = true,
                            CanUseApp = true,
                            HasAllPrivelage = true,
                            RoleName = "Administrator",
                            UUID = new Guid("e12d1ec2-9904-40aa-be78-748198ba8a79")
                        },
                        new
                        {
                            Id = 2,
                            AppName = "ControlReport",
                            AppUuid = new Guid("37f9aec4-3090-473d-a771-159a4bee8c47"),
                            CanBeEdited = false,
                            CanCreateDeviation = false,
                            CanCreateEcr = false,
                            CanCreateIntervention = false,
                            CanCreateReference = false,
                            CanCreateTask = false,
                            CanDeleteDeviation = false,
                            CanDeleteEcr = false,
                            CanDeleteIntervention = false,
                            CanDeleteReference = false,
                            CanDeleteTask = false,
                            CanReadDeviation = true,
                            CanReadEcr = true,
                            CanReadIntervention = true,
                            CanReadReference = true,
                            CanReadTask = true,
                            CanUpdateDeviation = false,
                            CanUpdateEcr = false,
                            CanUpdateIntervention = false,
                            CanUpdateReference = false,
                            CanUpdateTask = false,
                            CanUseApp = true,
                            HasAllPrivelage = false,
                            RoleName = "User",
                            UUID = new Guid("896a0c71-e219-47aa-8b99-78090f1bcffa")
                        });
                });

            modelBuilder.Entity("GlobalManagement.Models._DefaultModels._Roles._GlobalRoles.DefaultGlobalRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AppUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanAccessGlobal")
                        .HasColumnType("bit");

                    b.Property<bool>("CanBeEdited")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateGroup")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteGroup")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdateGroup")
                        .HasColumnType("bit");

                    b.Property<bool>("CreateCustomRole")
                        .HasColumnType("bit");

                    b.Property<bool>("CreateUser")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteCustomRole")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteUser")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UpdateCustomRole")
                        .HasColumnType("bit");

                    b.Property<bool>("UpdateUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("GlobalPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppName = "GlobalApp",
                            AppUuid = new Guid("899960d1-f610-4c7d-878e-b505b5fe7209"),
                            CanAccessGlobal = true,
                            CanBeEdited = false,
                            CanCreateGroup = true,
                            CanDeleteGroup = true,
                            CanUpdateGroup = true,
                            CreateCustomRole = true,
                            CreateUser = true,
                            DeleteCustomRole = true,
                            DeleteUser = true,
                            RoleName = "Administrator",
                            UpdateCustomRole = true,
                            UpdateUser = true,
                            Uuid = new Guid("02cc50eb-c871-41e0-87b0-b44c8d4a00d5")
                        },
                        new
                        {
                            Id = 2,
                            AppName = "GlobalApp",
                            AppUuid = new Guid("899960d1-f610-4c7d-878e-b505b5fe7209"),
                            CanAccessGlobal = false,
                            CanBeEdited = false,
                            CanCreateGroup = false,
                            CanDeleteGroup = false,
                            CanUpdateGroup = false,
                            CreateCustomRole = false,
                            CreateUser = false,
                            DeleteCustomRole = false,
                            DeleteUser = false,
                            RoleName = "User",
                            UpdateCustomRole = false,
                            UpdateUser = false,
                            Uuid = new Guid("cddb4738-26c8-4792-9950-e250dcde45b7")
                        });
                });

            modelBuilder.Entity("GlobalManagement.Models._DefaultModels._User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("nvarchar(28)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pin")
                        .HasMaxLength(16)
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Card = "1234",
                            CreatedDate = new DateTime(2024, 12, 18, 8, 41, 10, 207, DateTimeKind.Local).AddTicks(1389),
                            Email = "zyw2.automatyzacja@gmail.com",
                            FirstName = "admin",
                            FullName = "admin admin",
                            IsActive = true,
                            LastName = "admin",
                            Password = "$2a$11$vY11dmT920AhDeXUW.bLW.hlkHu3br/vwj.Ayu28GMouE9/XoFACu",
                            Pin = 1234,
                            UserName = "admin",
                            Uuid = new Guid("231811de-77b8-4637-9118-c6544126b68b")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
